### ISSUE TITLE
(Add title for bug report)

### ISSUE THREAD

**Issue by cicada-dispatch** [daniellanner/snow-for-unity-facade#1]
# (Add title for bug report)

(1-2 sentences what this bug is about.)
- Unity 2020.3.14f1

## Description

(A detailed summary of the unexpected behaviour.)
### Expected Behaviour

(A clear and concise description of what you expected to happen.)
## SnowFS Log file

```txt
1634408858919 +0400 $> init: initialized at D:/git/snowfs-for-unity
1634408869800 +0400 $> commit: Created Project
1634408878159 +0400 $> commit: Initial version
```

## Tasks

- [ ] Ensure report title follows contribution rules
- [ ] Delete non-applicable description
- [ ] I would like to work on a fix for this bug
